name: CI

on:
  pull_request: # Trigger on all pull requests

jobs:
  build:
    runs-on: ubuntu-latest # This will be overridden by the container spec below
    container:
      image: oven/bun:1.2 # Use the specified Docker image

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: bun install

    - name: Run sv check
      run: bun run check

    - name: Run build
      run: bun run build
